name: clash-chip8
version: 0.1.0
category: hardware, emulator

custom-setup:
  dependencies:
    - base
    - Cabal
    - clashilator

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib
  - retroclash-sim

  - clash-shake

  - lens
  - mtl
  - transformers
  - barbies ^>= 2.0.1
  - barbies-th
  - array
  - bytestring
  - sdl2
  - temporary
  - extra
  - optparse-applicative
  - template-haskell

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeInType
  - TypeOperators

ghc-options:
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

source-dirs:
  - src

flags:
  verilator:
    manual: True
    default: False

executables:
  chip8:
    main: simulator.hs

  chip8-board:
    main: simulator-board.hs

  chip8-vga:
    main: simulator-vga.hs
    when:
    - condition: flag(verilator)
      then:
        verbatim:
          x-clashilator-top-is: CHIP8.VideoTestBench
          x-clashilator-clock: CLK_25MHZ
          x-clashilator-clash-flags: -fclash-inline-limit=400
      else:
        buildable: false
