resolver: clash-1.4.2.yaml

extra-deps:
  - clash-shake
  - clashilator
  - retroclash-lib
  - retroclash-sim

  - barbies-2.0.1.0
  - barbies-th-0.1.2
  - lift-type-0.1.0.0
  - monoidal-containers-0.6.0.1
